on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

name: PHP Unit

jobs:
  Unit:
    runs-on: ubuntu-latest
    env:
      XDEBUG_MODE: coverage

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run unit tests
        run: vendor/bin/phpunit --testsuite unit

      - name: Upload coverage reports
        uses: codecov/codecov-action@v3
        with:
          files: phpunit.cobertura.xml
