on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

name: PHP Legacy Integration (Keycloak compatibility)

jobs:
  Integration:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        keycloak: [13.0.0, 14.0.0, 15.0.0, 16.0.0, 17.0.0-legacy, 18.0.0-legacy]
        php: [ 8.1 ]

    env:
      KEYCLOAK_VERSION: ${{ matrix.keycloak }}
      KEYCLOAK_BASE_URL: 'http://localhost:8080/auth'
      XDEBUG_MODE: coverage

    services:
      keycloak:
        image: quay.io/keycloak/keycloak:${{ matrix.keycloak }}
        env:
          KEYCLOAK_USER: admin
          KEYCLOAK_PASSWORD: admin
        ports:
          - '8080:8080'

    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Wait for Keycloak
        uses: iFaxity/wait-on-action@v1
        with:
          resource: ${{ env.KEYCLOAK_BASE_URL }}

      - name: Run integration tests
        run: vendor/bin/phpunit --testsuite integration
