on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

name: PHP Unit

jobs:
  Unit:
    runs-on: ubuntu-latest
    env:
      XDEBUG_MODE: coverage

    strategy:
      matrix:
        php: [ 8.1, 8.2, 8.3 ]

    steps:
      - uses: actions/checkout@v2

      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: pcov

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run unit tests
        run: vendor/bin/phpunit --testsuite unit

      - name: Upload coverage reports
        uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: true
          files: phpunit.cobertura.xml
          token: ${{ secrets.CODECOV_TOKEN }}
